### ISSUE TITLE
Mapping champs ODSPEP 2023 <=> format intermédiaire

### ISSUE THREAD

**Issue by ColinMaudry** [betagouv/data-inclusion#17]
Les données ODSPEP sont converties au format data.inclusion à partir d'un format intermédiaire, une version normalisée de fichiers Excel envoyés en 2022.

Fichier Excel => format intermédiaire normalisé => data.inclusion

Afin de faciliter le chargement des données reçues en janvier 2023, nous convertissons ces données au même format normalisé. Ce format normalisé se compose de plusieurs fichiers :

- ressources.csv
- contacts.csv
- familles.csv
- horaires.csv
- sous-categories.csv

Première étape : faire le mapping.

### resources.csv

<table>
<tr>
    <th>Champ cible
    <th>Champ source 2023
    <th>Commentaire
<tr>
	<td>ID_RES</td>
	<td>RES_PARTENARIALE.ID_RES
	<td>
<tr>
	<td>LIBELLE_SERVICE</td>
	<td>RES_PARTENARIALE.LIBELLE_COURT_RSP
	<td>
<tr>
	<td>DESCRIPTION_SERVICE</td>
	<td>RES_PARTENARIALE.SERVICE_DESCRIPTION_RSP
	<td>
<tr>
	<td>STRUCTURE</td>
	<td>RES_PARTENARIALE.NOM_STRUCTURE_RSP
	<td>
<tr>
	<td>SERVICE_RSP
	<td>RES_PARTENARIALE.SERVICE_RSP
    <td>
<tr>
	<td>ID_ADR
	<td>RES_PARTENARIALE.ID_ADR
    <td>
<tr>
	<td>L1_IDENTIFICATION_DEST_ADR
	<td>ADRESSE.L1_IDENTIFICATION_DEST_ADR
    <td>
<tr>
	<td>L2_IDENTITE_DEST_ADR
	<td>ADRESSE.L2_IDENTITE_DEST_ADR
    <td>
<tr>
	<td>L4_NUMERO_LIB_VOIE_ADR
	<td>ADRESSE.L4_NUMERO_LIB_VOIE_ADR
    <td>
<tr>
    <td>L3_COMPLEMENT_ADR
	<td>ADRESSE.L3_COMPLEMENT_ADR
    <td>
<tr>
    <td>L5_MENTION_ADR
	<td>ADRESSE.L5_MENTION_ADR
    <td>
<tr>
    <td>L7_PAYS_ADR
	<td>ADRESSE.L7_PAYS_ADR
    <td>
<tr>
    <td>LATITUDE_ADR
	<td>ADRESSE.LATITUDE_ADR
    <td>
<tr>
    <td>LONGITUDE_ADR
	<td>ADRESSE.LONGITUDE_ADR
    <td>
<tr>
    <td>EST_NORMALISEE_ADR
	<td>ADRESSE.EST_NORMALISEE_ADR
    <td>
<tr>
    <td>CODE_COMMUNE_ADR
	<td>ADRESSE.CODE_COMMUNE_ADR
    <td>
<tr>
    <td>CODE_POSTAL_ADR
	<td>ADRESSE.CODE_POSTAL_ADR
    <td>
<tr>
    <td>LIBELLE_COMMUNE_ADR
	<td>ADRESSE.LIBELLE_COMMUNE_ADR
    <td>
<tr>
    <td>DATE DERNIERE MAJ
	<td>RES_PARTENARIALE.DATE_DERNIERE_MODIF_RSP
    <td>
</table>

**Comment by vmttn** [comment]
Tu peux aussi faire évoluer les champs cibles attendus par le mapping actuel. Ils ont été définis en se basant sur le précédent export (qui est inclus dans le dernier export) et n'ont pas d'autres justification.

**Comment by ColinMaudry** [comment]
Après en avoir discuté, on va arrêter de passer par des fichiers intermédiaires. Les fichiers que l'on reçoit de Pôle emploi ont une structure normalisée qui est quasiment stable. Donc on peut les convertir directement au bon format.
